### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by HAPPYFUNSIGHT** [zhouyupeng/webpack5-vue3#4]
[webpack-cli] Unable to load '@webpack-cli/serve' command
[webpack-cli] TypeError: options.forEach is not a function
![image](https://user-images.githubusercontent.com/45377308/141977723-d4997555-c6ef-4056-b756-6c4452fb926e.png)

**Comment by weitemi** [comment]
我也是

**Comment by qiuyu303** [comment]
@weitemi  @HAPPYFUNSIGHT   搜下这个 [webpack-cli] Unable to load '@webpack-cli/serve' command  网上有很多解决办法，或者是删了node_modules 用几种方式重新装下依赖
